[general]
listening_address = "0.0.0.0:8000"
domain = "lacontrevoie.fr"
full_name = "La Contre-Voie"
short_name = "La Contre-Voie"
support_url = "https://lacontrevoie.fr/services/mail/"

[autodiscover]
enabled = true
# The socket/virtual host serving this service
address = "https://autodiscover.42l.fr"
# TTL in hours
ttl = 48

[autoconfig]
enabled = true
support_descr = "Guide on using the La Contre-Voie mail service"

# Information about the fields below
# login: "Localpart" (abc) or "EmailDom" (abc@mydomain.fr)
# encryption: "None", "SSL" or "StartTLS"
# microsoft_password_encryption: to use proprietary SPA protocol
# standard_password_encryption: to use CRAM-MD5 for password auth
# If you are unsure about this information, leave the default values

[mobileconfig]
description = "Email configuration for La Contre-Voie's mail server"

[imap]
enabled = true
hostname = "mail.42l.fr"
port = 143
login = "EmailDom"
encryption = "starttls"
microsoft_password_encryption = false
standard_password_encryption = false

[imaps]
enabled = true
hostname = "mail.42l.fr"
port = 993
login = "EmailDom"
encryption = "ssl"
microsoft_password_encryption = false
standard_password_encryption = false

[pop]
enabled = true
hostname = "mail.42l.fr"
port = 110
login = "EmailDom"
encryption = "starttls"
microsoft_password_encryption = false
standard_password_encryption = false

[pops]
enabled = true
hostname = "mail.42l.fr"
port = 995
login = "EmailDom"
encryption = "ssl"
microsoft_password_encryption = false
standard_password_encryption = false

[smtp]
enabled = false
hostname = "mail.42l.fr"
port = 25
login = "EmailDom"
encryption = "none"
microsoft_password_encryption = false
standard_password_encryption = false

[smtps]
enabled = true
hostname = "mail.42l.fr"
port = 465
login = "EmailDom"
encryption = "ssl"
microsoft_password_encryption = false
standard_password_encryption = false

[submission]
enabled = true
hostname = "mail.42l.fr"
port = 587
login = "EmailDom"
encryption = "starttls"
microsoft_password_encryption = false
standard_password_encryption = false
