name: Build and push
on: [ push ]

jobs:
  release:
    runs-on: runner_image
    steps:
      - name: Checkout
        run: git clone ${{ gitea.server_url }}/${{ gitea.repository }} .

      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v3
        with:
          config-inline: |
            [registry."${{ vars.DOCKER_REGISTRY }}"]

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ vars.DOCKER_REGISTRY }}/${{ gitea.repository }}:latest,${{ vars.DOCKER_REGISTRY }}/${{ gitea.repository }}:${{ gitea.sha }}
